
--Q1--BEGIN
-- Which channel is most frequently used for transactions?
		select top 1 Store_type as Channel
		from Transactions
		group by Store_type
		order by count(Store_type) desc;

--Q1--END

--Q2--BEGIN
-- What is the count of Male and Female customers in the database?
		select Gender, count(Gender)
		from Customer
		where Gender is not null
		group by Gender;

--Q2--END

--Q3--BEGIN
-- From which city do we have the maximum number of customers and how many?
		select top 1 city_code as CITY,count(customer_Id) as [No of Customer]
		from Customer
		where city_code is not Null
		group by city_code 
		order by [No of Customer] desc;

--Q3--END

--Q4--BEGIN
-- How many sub-categories are there under the Books category?
		select prod_cat,count(prod_subcat) as [No Of Sub Category]
		from prod_cat_info
		where prod_cat='books'
		group by prod_cat;

--Q4--END

--Q5--BEGIN
-- What is the maximum quantity of products ever ordered?
		select max(Qty) as [Maximum Quantity]
		from Transactions;

--Q5--END

--Q6--BEGIN
-- What is the net total revenue generated in categories Electronics and Books?
		select b.prod_cat, sum(total_amt) as [Total Revenue]
		from Transactions as a
		inner join prod_cat_info as b
		on a.prod_cat_code=b.prod_cat_code and a.prod_subcat_code=b.prod_sub_cat_code
		where b.prod_cat in ('Electronics','Books')
		group by b.prod_cat

--Q6--END

--Q7--BEGIN
-- How many customers have >10 transactions with us, excluding returns?
		select count(cust_id) as [No of Customer which has more 10 Transacation]
		from(
			  select cust_id,count(cust_id) as counts
			  from Transactions 
			  where qty>0
			  group by cust_id
		    ) 
		as t
		where counts>10

--Q7--END

--Q8--BEGIN
-- What is the combined revenue earned from the “Electronics” & “Clothing” categories, from “Flagship stores”?
		select sum(total_amt) as [Total Revenue Generated By Electonics & Clothings]
		from Transactions as a
		inner join prod_cat_info as b
		on a.prod_cat_code=b.prod_cat_code and a.prod_subcat_code=b.prod_sub_cat_code
		where b.prod_cat in ('Electronics','Clothing') and Store_type='Flagship Store';

--Q8--END

--Q9--BEGIN
-- What is the total revenue generated from “Male” customers in “Electronics” category?
-- Output should display total revenue by prod sub-cat.
		select b.prod_cat,b.prod_subcat,sum(a.total_amt) as [Total Revenue]
		from Transactions as a
		inner join prod_cat_info as b
		on a.prod_cat_code=b.prod_cat_code and a.prod_subcat_code=b.prod_sub_cat_code
		inner join Customer as c
		on c.customer_Id=a.cust_id
		where c.Gender='M' and b.prod_cat='Electronics'
		group by b.prod_cat,b.prod_subcat;

--Q9--END

--Q10--BEGIN
-- What is percentage of sales and returns by product sub category (top 5 subcategories by sales)?
		with top_sales
		  as( 
		      select top 5  a.prod_cat_code,a.prod_subcat_code,b.prod_cat,b.prod_subcat,sum(a.total_amt) as total_sales
			  from Transactions as a
			  inner join prod_cat_info as b
			  on a.prod_cat_code=b.prod_cat_code and a.prod_subcat_code=b.prod_sub_cat_code
			  group by a.prod_cat_code,a.prod_subcat_code,b.prod_cat,b.prod_subcat
			  order by total_sales desc
		    ),
		return_sale
		  as(
		      select  b.prod_subcat,total_sales,sum(a.total_amt) as return_sales
			  from Transactions as a
			  inner join top_sales as b
			  on a.prod_cat_code=b.prod_cat_code and a.prod_subcat_code=b.prod_subcat_code
			  where a.total_amt<0
			  group by a.prod_cat_code,a.prod_subcat_code,b.prod_cat,b.prod_subcat,total_sales
		    )
		select prod_subcat,total_sales/(select sum(total_amt) from Transactions)*100 as [% Sales],
		return_sales/(select sum(total_amt) from Transactions)*100 as [% Return Sales]
		from return_sale

--Q10--END

--Q11--BEGIN
-- For customers aged 25–35, net total revenue in last 30 days from max transaction date?
		select sum(a.total_amt) as [Total revenue of the last 30 days of those aged between 10 to 25]
		from Transactions as a
		inner join Customer as b
		on a.cust_id=b.customer_Id
		where datediff(YEAR,b.DOB,(select max(dob)from Customer)) between 10 and 25 
		and dateadd(day,-30,(select max(tran_date) from Transactions)) < a.tran_date

--Q11--END

--Q12--BEGIN
-- Which product category has seen the max value of returns in the last 3 months of transactions?
		select top 1 b.prod_cat
		from Transactions as a
		inner join prod_cat_info as b
		on a.prod_cat_code=b.prod_cat_code and a.prod_subcat_code=b.prod_sub_cat_code
		where a.Qty<0 and dateadd(MONTH,-3,(select max(tran_date)from Transactions))<a.tran_date
		group by a.prod_cat_code,b.prod_cat
		order by sum(a.Qty);

--Q12--END

--Q13--BEGIN
-- Which store-type sells the maximum products; by value of sales amount and by quantity sold?
		with sales as(
		select Store_type ,sum(total_amt) as [Sales Amount],
		dense_rank() over(order by sum(total_amt) desc) as ranks
		from Transactions
		group by Store_type
		--order by [Sales Amount] desc
		),
		quantity as(
		select Store_type ,sum(Qty) as [Quantity Sold],
		dense_rank() over(order by sum(total_amt) desc) as ranking
		from Transactions
		group by Store_type
		--order by [Quantity Sold] desc
		)
		select a.Store_type as [Store by Sales],b.Store_type as [Store by Quantity]
		from sales as a , quantity as b
		where ranks=1 and ranking=1

--Q13--END

--Q14--BEGIN
-- What are the categories for which average revenue is above the overall average?
		select b.prod_cat as[Product Category]
		from Transactions as a
		inner join prod_cat_info as b
		on a.prod_cat_code=b.prod_cat_code and a.prod_subcat_code=b.prod_sub_cat_code
		group by a.prod_cat_code,b.prod_cat
		having avg(a.total_amt)>(select avg(total_amt) from Transactions);

--Q14--END

--Q15--BEGIN
-- Average and total revenue by each subcategory for top 5 categories (by quantity sold)?
		with top_category
		  as (
			   select top 5 a.prod_cat_code,b.prod_cat,sum(Qty) as quantity
			   from Transactions as a
			   inner join prod_cat_info as b
			   on a.prod_cat_code=b.prod_cat_code and a.prod_subcat_code=b.prod_sub_cat_code
			   group by a.prod_cat_code ,b.prod_cat
			   order by quantity desc
			 )
		
		select b.prod_cat,b.prod_subcat,sum(a.total_amt) as [Total Revenue],avg(total_amt) as [Average Revenue]
		from Transactions as a 
		inner join prod_cat_info as b
		on a.prod_cat_code=b.prod_cat_code and a.prod_subcat_code=b.prod_sub_cat_code
		inner join top_category as c
		on c.prod_cat_code=a.prod_cat_code
		group by b.prod_cat,b.prod_subcat
		order by b.prod_cat,b.prod_subcat;
		
--Q15--END

--=============================================================================================================================--
select * from Customer
select * from prod_cat_info
select * from Transactions
